version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main_2}"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      #- SERVICES=SQS,SNS
      - DEFAULT_REGION=sa-east-1
      - HOSTNAME_EXTERNAL=awslocal
      #- EAGER_SERVICE_LOADING=true
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"